# Configuration principale
owner: webcosa # Mettez votre pseudo GitHub ici
repo: status-page # Mettez le nom de votre dépôt GitHub ici (ex: status-page)

sites:
  - name: Webcosa Website
    url: https://www.webcosa.com
  - name: Webcosa Dev
    url: https://dev.webcosa.com
  - name: Webcosa Store
    url: https://store.webcosa.com
  - name: Webcosa CMS
    url: https://cms.webcosa.com

status-website:
  cname: status.webcosa.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Webcosa Status
  introTitle: "**Statut des services Webcosa**"
  introMessage: "Cette page affiche en temps réel l'état de nos services, sites et API. Elle est entièrement automatisée."
  navbar:
    - title: Statut
      href: /
    - title: Webcosa Website
      href: https://webcosa.com
